"use strict";

export const TREE_SAVE_REQUEST = "TREE_SAVE_REQUEST";
export const TREE_SAVE_SUCCESS = "TREE_SAVE_SUCCESS";
export const TREE_SAVE_FAILURE = "TREE_SAVE_FAILURE";

export const TREE_ITEM_ADD = "TREE_ITEM_ADD";
export const TREE_ITEM_CHANGE = "TREE_ITEM_CHANGE";
export const TREE_ITEM_DELETE = "TREE_ITEM_DELETE";
export const TREE_ITEM_SELECT = "TREE_ITEM_SELECT";
export const TREE_ITEM_UPDATE = "TREE_ITEM_UPDATE";
export const TREE_ITEM_EXPAND = "TREE_ITEM_EXPAND";
export const TREE_ITEM_COLLAPSE = "TREE_ITEM_COLLAPSE";
export const TREE_ITEM_MOVE = "TREE_ITEM_MOVE";
